// Dynamic import to avoid SSR issues — jsPDF accesses browser globals at import time
let jsPDFModule: typeof import('jspdf') | null = null;
async function getJsPDF() {
  if (!jsPDFModule) {
    jsPDFModule = await import('jspdf');
  }
  return jsPDFModule.jsPDF;
}

interface ExportToPdfOptions {
  title: string;
  subtitle?: string;
  content: string;
  companyName: string;
  date?: string;
  filename?: string;
}

const NAVY = '#0a1628';
const DARK_GRAY = '#1a2744';
const MEDIUM_GRAY = '#6b7280';
const LIGHT_GRAY = '#9ca3af';
const ACCENT = '#3b82f6';
const WHITE = '#ffffff';
const BLACK = '#111827';

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
const MARGIN_BOTTOM = 25;
const HEADER_HEIGHT = 18;
const FOOTER_HEIGHT = 15;

function addHeader(doc: any, companyName: string) {
  doc.setFillColor(NAVY);
  doc.rect(0, 0, PAGE_WIDTH, HEADER_HEIGHT, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(WHITE);
  doc.text(companyName.toUpperCase(), MARGIN_LEFT, 11.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(LIGHT_GRAY);
  doc.text('POWERED BY TELUM', PAGE_WIDTH - MARGIN_RIGHT, 11.5, { align: 'right' });
}

function addFooter(doc: any, date: string, pageNum: number, totalPages: number) {
  const y = PAGE_HEIGHT - 10;
  doc.setDrawColor(DARK_GRAY);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, y - 5, PAGE_WIDTH - MARGIN_RIGHT, y - 5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(MEDIUM_GRAY);
  doc.text(`Generated by Telum \u2022 ${date}`, MARGIN_LEFT, y);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - MARGIN_RIGHT, y, { align: 'right' });
}

function ensureSpace(doc: any, currentY: number, needed: number, companyName: string): number {
  if (currentY + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
    doc.addPage();
    addHeader(doc, companyName);
    return HEADER_HEIGHT + 10;
  }
  return currentY;
}

interface ParsedLine {
  type: 'h1' | 'h2' | 'h3' | 'bullet' | 'paragraph' | 'blank';
  text: string;
}

function parseMarkdown(content: string): ParsedLine[] {
  const lines = content.split('\n');
  const result: ParsedLine[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (line.trim() === '') {
      result.push({ type: 'blank', text: '' });
      continue;
    }

    if (line.startsWith('### ')) {
      result.push({ type: 'h3', text: line.slice(4).trim() });
    } else if (line.startsWith('## ')) {
      result.push({ type: 'h2', text: line.slice(3).trim() });
    } else if (line.startsWith('# ')) {
      result.push({ type: 'h1', text: line.slice(2).trim() });
    } else if (/^\s*[-*]\s+/.test(line)) {
      result.push({ type: 'bullet', text: line.replace(/^\s*[-*]\s+/, '').trim() });
    } else {
      result.push({ type: 'paragraph', text: line.trim() });
    }
  }

  return result;
}

function renderTextWithBold(doc: any, text: string, x: number, y: number, maxWidth: number, fontSize: number, baseStyle: string): number {
  // Split text into bold and non-bold segments
  const segments: { text: string; bold: boolean }[] = [];
  const boldRegex = /\*\*(.*?)\*\*/g;
  let lastIndex = 0;
  let match;

  while ((match = boldRegex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      segments.push({ text: text.slice(lastIndex, match.index), bold: false });
    }
    segments.push({ text: match[1], bold: true });
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) {
    segments.push({ text: text.slice(lastIndex), bold: false });
  }

  if (segments.length === 0) {
    segments.push({ text, bold: false });
  }

  // Flatten to plain text for wrapping calculation
  const plainText = segments.map(s => s.text).join('');
  doc.setFontSize(fontSize);
  doc.setFont('helvetica', baseStyle);
  const wrappedLines = doc.splitTextToSize(plainText, maxWidth) as string[];

  let currentY = y;

  for (const wrappedLine of wrappedLines) {
    // For each wrapped line, find which segments contribute to it
    let currentX = x;
    let remaining = wrappedLine;

    for (const segment of segments) {
      if (remaining.length === 0) break;

      // How much of this segment is in the current wrapped line
      const segText = segment.text;
      let consumed = '';

      for (let i = 0; i < segText.length && remaining.length > 0; i++) {
        if (segText[i] === remaining[0]) {
          consumed += remaining[0];
          remaining = remaining.slice(1);
        }
      }

      if (consumed) {
        doc.setFont('helvetica', segment.bold ? 'bold' : baseStyle);
        doc.text(consumed, currentX, currentY);
        currentX += doc.getTextWidth(consumed);
      }

      // Remove consumed characters from the segment for subsequent lines
      segment.text = segText.slice(consumed.length);
    }

    currentY += fontSize * 0.45;
  }

  return currentY;
}

export async function exportToPdf(options: ExportToPdfOptions): Promise<Blob> {
  const { title, subtitle, content, companyName, date, filename } = options;
  const displayDate = date || new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const JsPDF = await getJsPDF();
  const doc = new JsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // --- Title Page ---
  addHeader(doc, companyName);

  let y = HEADER_HEIGHT + 30;

  // Accent line
  doc.setFillColor(ACCENT);
  doc.rect(MARGIN_LEFT, y, 40, 1.5, 'F');
  y += 10;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(BLACK);
  const titleLines = doc.splitTextToSize(title, CONTENT_WIDTH) as string[];
  for (const line of titleLines) {
    doc.text(line, MARGIN_LEFT, y);
    y += 10;
  }
  y += 4;

  // Subtitle
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(MEDIUM_GRAY);
    const subLines = doc.splitTextToSize(subtitle, CONTENT_WIDTH) as string[];
    for (const line of subLines) {
      doc.text(line, MARGIN_LEFT, y);
      y += 6;
    }
    y += 4;
  }

  // Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(LIGHT_GRAY);
  doc.text(displayDate, MARGIN_LEFT, y);
  y += 6;

  // Company info
  doc.setFontSize(10);
  doc.setTextColor(LIGHT_GRAY);
  doc.text(`Prepared for ${companyName}`, MARGIN_LEFT, y);

  // --- Content pages ---
  doc.addPage();
  addHeader(doc, companyName);
  y = HEADER_HEIGHT + 10;

  const parsed = parseMarkdown(content);
  let blankCount = 0;

  for (const line of parsed) {
    if (line.type === 'blank') {
      blankCount++;
      if (blankCount <= 2) {
        y += 3;
      }
      continue;
    }
    blankCount = 0;

    switch (line.type) {
      case 'h1': {
        y = ensureSpace(doc, y, 16, companyName);
        y += 6;
        doc.setFillColor(ACCENT);
        doc.rect(MARGIN_LEFT, y - 4, 30, 1, 'F');
        y += 4;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.setTextColor(BLACK);
        const h1Lines = doc.splitTextToSize(line.text, CONTENT_WIDTH) as string[];
        for (const l of h1Lines) {
          y = ensureSpace(doc, y, 8, companyName);
          doc.text(l, MARGIN_LEFT, y);
          y += 7.5;
        }
        y += 4;
        break;
      }

      case 'h2': {
        y = ensureSpace(doc, y, 14, companyName);
        y += 4;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.setTextColor(DARK_GRAY);
        const h2Lines = doc.splitTextToSize(line.text, CONTENT_WIDTH) as string[];
        for (const l of h2Lines) {
          y = ensureSpace(doc, y, 7, companyName);
          doc.text(l, MARGIN_LEFT, y);
          y += 6.5;
        }
        y += 3;
        break;
      }

      case 'h3': {
        y = ensureSpace(doc, y, 12, companyName);
        y += 3;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(DARK_GRAY);
        const h3Lines = doc.splitTextToSize(line.text, CONTENT_WIDTH) as string[];
        for (const l of h3Lines) {
          y = ensureSpace(doc, y, 6, companyName);
          doc.text(l, MARGIN_LEFT, y);
          y += 5.5;
        }
        y += 2;
        break;
      }

      case 'bullet': {
        const bulletIndent = 6;
        y = ensureSpace(doc, y, 6, companyName);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(BLACK);

        // Bullet character
        doc.setFillColor(ACCENT);
        doc.circle(MARGIN_LEFT + 2, y - 1.2, 1, 'F');

        // Text - handle bold
        const bulletWidth = CONTENT_WIDTH - bulletIndent;
        const cleanText = line.text.replace(/\*\*(.*?)\*\*/g, '$1');
        const bulletLines = doc.splitTextToSize(cleanText, bulletWidth) as string[];

        for (let i = 0; i < bulletLines.length; i++) {
          y = ensureSpace(doc, y, 5, companyName);
          doc.text(bulletLines[i], MARGIN_LEFT + bulletIndent, y);
          y += 4.5;
        }
        y += 1;
        break;
      }

      case 'paragraph': {
        y = ensureSpace(doc, y, 6, companyName);
        const cleanPara = line.text.replace(/\*\*(.*?)\*\*/g, '$1');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(BLACK);
        const paraLines = doc.splitTextToSize(cleanPara, CONTENT_WIDTH) as string[];
        for (const l of paraLines) {
          y = ensureSpace(doc, y, 5, companyName);
          doc.text(l, MARGIN_LEFT, y);
          y += 4.5;
        }
        y += 2;
        break;
      }
    }
  }

  // --- Add footers to all pages ---
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, displayDate, i, totalPages);
  }

  // Generate blob
  const blob = doc.output('blob');
  return blob;
}

export async function downloadPdf(options: ExportToPdfOptions): Promise<void> {
  const blob = await exportToPdf(options);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeFilename = (options.filename || options.title)
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase();
  a.download = `${safeFilename}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
